[package]
name = "prooheckcp/countryservice"
description = "CountryService is a library that allows you to obtain information about the users countries. Gives you their country name, flag emoji and flag image (Decal/Image). You can read it's documentation at: https://github.com/prooheckcp/CountryService"
version = "0.1.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["Prooheckcp"]
exclude = ["**"]
include = [
    "default.project.json", 
    "CountryService", 
    "wally.lock", 
    "wally.toml",
    "CountryService/*"
]